#############################################################################
# Makefile for building: STU_LOGIN
# Generated by qmake (2.01a) (Qt 4.8.6) on: ?? 11? 15 09:41:25 2015
# Project:  STU_LOGIN.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile STU_LOGIN.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		loginwindow.cpp \
		stulogin.cpp \
		account.cpp \
		suspendingwindow.cpp \
		auxiliary.cpp \
		exaccount.cpp \
		clientdialog.cpp moc_loginwindow.cpp \
		moc_stulogin.cpp \
		moc_suspendingwindow.cpp \
		moc_clientdialog.cpp \
		qrc_icons.cpp
OBJECTS       = main.o \
		loginwindow.o \
		stulogin.o \
		account.o \
		suspendingwindow.o \
		auxiliary.o \
		exaccount.o \
		clientdialog.o \
		moc_loginwindow.o \
		moc_stulogin.o \
		moc_suspendingwindow.o \
		moc_clientdialog.o \
		qrc_icons.o
DIST          = myRc.rc \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		STU_LOGIN.pro
QMAKE_TARGET  = STU_LOGIN
DESTDIR       = 
TARGET        = STU_LOGIN

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_loginwindow.h ui_suspendingwindow.h ui_clientdialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: STU_LOGIN.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtNetwork.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile STU_LOGIN.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtNetwork.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile STU_LOGIN.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/STU_LOGIN1.0.0 || $(MKDIR) .tmp/STU_LOGIN1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/STU_LOGIN1.0.0/ && $(COPY_FILE) --parents loginwindow.h stulogin.h account.h suspendingwindow.h auxiliary.h exaccount.h clientdialog.h .tmp/STU_LOGIN1.0.0/ && $(COPY_FILE) --parents resource/icons/icons.qrc .tmp/STU_LOGIN1.0.0/ && $(COPY_FILE) --parents main.cpp loginwindow.cpp stulogin.cpp account.cpp suspendingwindow.cpp auxiliary.cpp exaccount.cpp clientdialog.cpp .tmp/STU_LOGIN1.0.0/ && $(COPY_FILE) --parents loginwindow.ui suspendingwindow.ui clientdialog.ui .tmp/STU_LOGIN1.0.0/ && (cd `dirname .tmp/STU_LOGIN1.0.0` && $(TAR) STU_LOGIN1.0.0.tar STU_LOGIN1.0.0 && $(COMPRESS) STU_LOGIN1.0.0.tar) && $(MOVE) `dirname .tmp/STU_LOGIN1.0.0`/STU_LOGIN1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/STU_LOGIN1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_loginwindow.cpp moc_stulogin.cpp moc_suspendingwindow.cpp moc_clientdialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_loginwindow.cpp moc_stulogin.cpp moc_suspendingwindow.cpp moc_clientdialog.cpp
moc_loginwindow.cpp: ui_loginwindow.h \
		stulogin.h \
		exaccount.h \
		account.h \
		suspendingwindow.h \
		ui_suspendingwindow.h \
		clientdialog.h \
		loginwindow.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) loginwindow.h -o moc_loginwindow.cpp

moc_stulogin.cpp: exaccount.h \
		stulogin.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) stulogin.h -o moc_stulogin.cpp

moc_suspendingwindow.cpp: ui_suspendingwindow.h \
		suspendingwindow.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) suspendingwindow.h -o moc_suspendingwindow.cpp

moc_clientdialog.cpp: clientdialog.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) clientdialog.h -o moc_clientdialog.cpp

compiler_rcc_make_all: qrc_icons.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_icons.cpp
qrc_icons.cpp: resource/icons/icons.qrc \
		resource/icons/mainicon.png
	/usr/lib/x86_64-linux-gnu/qt4/bin/rcc -name icons resource/icons/icons.qrc -o qrc_icons.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_loginwindow.h ui_suspendingwindow.h ui_clientdialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_loginwindow.h ui_suspendingwindow.h ui_clientdialog.h
ui_loginwindow.h: loginwindow.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic loginwindow.ui -o ui_loginwindow.h

ui_suspendingwindow.h: suspendingwindow.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic suspendingwindow.ui -o ui_suspendingwindow.h

ui_clientdialog.h: clientdialog.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic clientdialog.ui -o ui_clientdialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp loginwindow.h \
		ui_loginwindow.h \
		stulogin.h \
		exaccount.h \
		account.h \
		suspendingwindow.h \
		ui_suspendingwindow.h \
		clientdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

loginwindow.o: loginwindow.cpp loginwindow.h \
		ui_loginwindow.h \
		stulogin.h \
		exaccount.h \
		account.h \
		suspendingwindow.h \
		ui_suspendingwindow.h \
		clientdialog.h \
		auxiliary.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o loginwindow.o loginwindow.cpp

stulogin.o: stulogin.cpp stulogin.h \
		exaccount.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stulogin.o stulogin.cpp

account.o: account.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o account.o account.cpp

suspendingwindow.o: suspendingwindow.cpp suspendingwindow.h \
		ui_suspendingwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o suspendingwindow.o suspendingwindow.cpp

auxiliary.o: auxiliary.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o auxiliary.o auxiliary.cpp

exaccount.o: exaccount.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o exaccount.o exaccount.cpp

clientdialog.o: clientdialog.cpp clientdialog.h \
		ui_clientdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o clientdialog.o clientdialog.cpp

moc_loginwindow.o: moc_loginwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_loginwindow.o moc_loginwindow.cpp

moc_stulogin.o: moc_stulogin.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_stulogin.o moc_stulogin.cpp

moc_suspendingwindow.o: moc_suspendingwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_suspendingwindow.o moc_suspendingwindow.cpp

moc_clientdialog.o: moc_clientdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_clientdialog.o moc_clientdialog.cpp

qrc_icons.o: qrc_icons.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_icons.o qrc_icons.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

